# THIS FILE IS MANAGED BY ANSIBLE, ALL CHANGES WILL BE LOS

logger:
    level: trace
    log: /var/log/clickhouse-server/clickhouse-server.log
    errorlog: /var/log/clickhouse-server/clickhouse-server.err.log
    size: 1000M
    count: 10
http_port: 8123
tcp_port: 9000
mysql_port: 9004
postgresql_port: 9005
interserver_http_port: 9009
max_connections: 4096
mark_cache_size: 5368709120
default_profile: "default"
default_database: "default"
user_directories:
  users_xml:
    path: users.yaml
  local_directory:
    path: /var/lib/clickhouse/access/
